### ISSUE TITLE
Ne marche pas

### ISSUE THREAD

**Issue by Horgix** [nekonyuu/couroux-sync#1]
Votre produit ne marche pas, merci de faire le nécessaire.

Cdlt

**Comment by nekonyuu** [comment]
Ce produit répond aux plus hauts standards de qualité connus à ce jour, merci de décrire votre besoin au plus vite.

**Comment by nekonyuu** [comment]
En l'absence de réponse ces 5 dernières minutes, je ferme le ticket, merci d'en ouvrir un nouveau si besoin.

**Comment by Horgix** [comment]
> Ce produit répond aux plus hauts standards de qualité connus à ce jour

Je suis ravis de lire ces mots; pourriez vous me fournir la preuve de la certification ISO 9001 de la gestion de ce projet ?

> merci de décrire votre besoin au plus vite.

Mon besoin est simple, et j'attends de vous, en tant que partenaire d'excellence, que vous sachiez l'anticiper et le comprendre. Si ce n'est pas le cas et dans la mesure où vous ne m'avez pas demandé cette description de besoin en amont, il faudra que je revois mes attentes.

Pour rappel, mon besoin est le suivant : j'ai besoin de pouvoir avoir un Internet hautement disponible, et j'attends de couroux-sync qu'il y réponde et me livre le café tous les matins à 9h, là encore de manière hautement disponible.

Dans l'attente de votre efficacité,

Cdlt,

**Comment by Horgix** [comment]
Par ailleurs, je suis outré que mon problème soit ignoré et cette issue fermée. Merci de la ré-ouvrir au plus vite afin de respecter vos engagements de support.

**Comment by Ahuri3** [comment]
Hello, I logged into the system and got an error. Can you explain what is the next step ? I need it to work by tommorow.

**Comment by apognu** [comment]
@Ahuri3 : t'as essayé de débrancher et de rebrancher Internet ?
